#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NotificatorApp.Resource", IsApplication=true)]

namespace NotificatorApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int settingsButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int startServiceButton = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int Pref_battery_allert_level_summary = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Pref_battery_allert_level_title = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int Pref_battery_allert_summary = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int Pref_battery_allert_title = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int Pref_battery_settings = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int Pref_battery_track_battery_status_summary = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int Pref_battery_track_battery_status_title = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int Pref_battery_track_summary = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int Pref_battery_track_title = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int Pref_send_information_time_interval_summary = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Pref_send_information_time_interval_title = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int Pref_sms_category_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Pref_sms_track_summary = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int Pref_sms_track_title = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int Pref_time_interval = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int Setting_button_name = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Start_service_button_name = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preference = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
